
import type { Timestamp as FirebaseTimestamp } from 'firebase/firestore'; // Use type import for Timestamp
import { FieldValue } from 'firebase/firestore'; // Use regular import for FieldValue
export interface User {
  id: string;
  username: string;
  name?: string;
  email?: string;
  phoneNumber?: string;
  avatarUrl?: string;
  bio?: string;
  location?: string;
  produce?: string[];
  followersCount?: number;
  followingCount?: number;
  postCount?: number;
  profileSetupComplete?: boolean;
  languageSelected?: boolean;
  languagePreference?: string;
  createdAt?: FirebaseTimestamp | FieldValue | undefined;
}

export interface Post {
  id: string;
  userId: string; // For easier querying
  user: Pick<User, 'id' | 'username' | 'name' | 'avatarUrl' | 'location'>; // Denormalized user data
  imageUrl?: string;
  caption: string;
  hashtags?: string[];
  likesCount: number;
  commentsCount: number;
  createdAt: FirebaseTimestamp;
}

export interface Comment {
  id: string;
  user: Pick<User, 'id' | 'username' | 'name' | 'avatarUrl'>;
  postId: string;
  text: string;
  createdAt: FirebaseTimestamp;
  parentId?: string | null;
  replies?: Comment[];
  replyCount?: number;
  likesCount?: number;
}

export interface NavLink {
  href: string;
  label: string;
  icon?: JSX.Element;
  badgeCount?: number; // Optional: for notification/message counts
}

export interface MandiListing {
  id: string;
  name: string;
  category: string;
  description?: string;
  details?: string;
  quantity: string;
  price: string;
  imageUrls: string[];
  aiHint: string;
  seller: Pick<User, 'id' | 'username' | 'name' | 'avatarUrl'>;
  sellerId: string;
  location: string;
  createdAt: FirebaseTimestamp;
}

// For UI display after fetching and converting timestamp
export interface DisplayMandiListing extends Omit<MandiListing, 'createdAt'> {
  listedDate: string; // Formatted date string
}

// For UI display after fetching and converting timestamp
export interface DisplayBuyerRequirement extends Omit<BuyerRequirement, 'createdAt'> {
  postedDate: string; // Formatted date string
}


export interface ChatMessage {
  id: string; // Firestore document ID
  senderId: string;
  text: string;
  timestamp: FirebaseTimestamp | string | undefined; // Firestore Timestamp, ISO Date string or formatted time string for display
  mediaUrl?: string;
  mediaType?: 'image' | 'video';
}

// Structure for data in Firestore 'conversations' collection
export interface FirestoreConversation {
  id?: string; // Document ID (e.g., uid1_uid2)
  participants: string[]; // Array of two user IDs, sorted alphabetically
  participantDetails: { // Denormalized data for quick display
    [userId: string]: Pick<User, 'id' | 'username' | 'name' | 'avatarUrl'>;
  };
  lastMessageText?: string;
  lastMessageTimestamp?: FirebaseTimestamp;
  lastMessageSenderId?: string;
}

// Structure for data in 'conversations/{convId}/messages' subcollection
export interface FirestoreMessage {
  id?: string; // Document ID (auto-generated by Firestore)
  senderId: string;
  text: string;
  timestamp: FirebaseTimestamp; // Server timestamp
  mediaUrl?: string;
  mediaType?: 'image' | 'video';
}

// For displaying list of conversations on /messages page
export interface DisplayConversation {
  id: string; // Conversation ID (e.g., uid1_uid2)
  otherParticipant: Pick<User, 'id' | 'username' | 'name' | 'avatarUrl'>;
  lastMessage: string;
  lastMessageTime: string; // Formatted string e.g., "2h ago" or "10:30 AM"
  unread?: boolean; 
}

// For Notifications
export interface ActorInfo {
  id: string;
  username: string;
  avatarUrl?: string;
  name?: string; // Added name for better display
}

export interface Notification {
  id: string; // Firestore document ID
  type: 'like' | 'comment' | 'follow';
  actor: ActorInfo; // User who performed the action
  postId?: string; // ID of the post, if applicable
  postImageUrl?: string; // For visual cue if it's a post-related notification
  postCaption?: string; // For context on post-related notifications
  commentText?: string; // Snippet of the comment
  timestamp: FirebaseTimestamp; // Firestore Timestamp when the notification occurred
  read: boolean; // If the notification has been read by the targetUser
  targetUserId: string; // The user ID for whom this notification is intended
}

export interface Yojna {
  id: string;
  name: string;
  description: string;
  eligibility?: string;
  benefits: string;
  link?: string;
  department?: string;
}

// For simplified disease display on Discover page
export interface DiscoverDisease {
  id:string;
  name: string;
  cropName: string; // e.g., "Tomato"
  cropSlug: string; // e.g., "tomato"
  symptomsSummary: string;
  imageUrl?: string;
  aiHint?: string;
}

export interface BuyerRequirement {
  id: string;
  postedBy: Pick<User, 'id' | 'username' | 'name' | 'avatarUrl'>;
  postedById: string;
  itemName: string;
  category: string;
  quantity: string;
  preferredLocation?: string;
  specifications?: string;
  createdAt: FirebaseTimestamp;
}
